apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harness-cis-dashboard
  namespace: harness-cis
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: harness-cis.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harness-cis-dashboard
            port:
              number: 5000
