apiVersion: v1
kind: Secret
metadata:
  name: harness-credentials
  namespace: harness-cis
type: Opaque
stringData:
  HARNESS_API_KEY: "${HARNESS_API_KEY}"
  HARNESS_ACCOUNT_ID: "${HARNESS_ACCOUNT_ID}"
